:- module(server, [server/1, stop_server/1]).

/** <module> HTTP front end.

    A second renderer over the same report/3 term the CLI prints, with no rule
    logic of its own.

    Concurrency: SWI's HTTP server is multithreaded, and everything below the
    report term is pure -- annotate/2 returns a term, no rule asserts anything,
    and the reference data is static and consulted at load. So no request state
    is shared and handlers need no locking. This is also why itineraries arrive
    as JSON rather than as Prolog fact files: consulting a fact file mutates
    the global database and could not be run concurrently.
*/

:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_json)).
:- use_module(library(http/http_cors)).
:- use_module(library(http/http_parameters)).
:- use_module(library(http/http_log)).
:- use_module(library(thread_pool)).
:- use_module(library(apply)).
:- use_module(library(time)).
:- use_module(library(yall)).

:- use_module('src/geo').
:- use_module('src/annotate').
:- use_module('src/validate').
:- use_module('src/io/json_in').
:- use_module('src/io/json_out').
:- use_module('src/io/earn_out').
:- use_module('src/io/route_out').
:- use_module('src/earn/kernel').
:- use_module('src/earn/registry').
:- use_module('data/limits').

% The bundled UI is served from this same origin, but CORS stays open so a UI
% under its own dev server can call the API too.
:- set_setting_default(http:cors, [*]).

% The UI is read into the program at load time rather than opened from disk on
% each request. Two reasons, both of which bit the first version:
%
%   * A path resolved with prolog_load_context/2 is fixed at *compile* time,
%     so a saved state or an image built anywhere but the deployment directory
%     served 404s for a file that was sitting right there. Reading at compile
%     time is the fix rather than the disease: what gets baked in is the
%     content, which is what we want, not a path that will not exist later.
%   * It removes the only filesystem access in the request path, so the
%     container can run read-only and the server needs no working directory.
%
% Every asset is held as a *string* of bytes rather than as text, so one code
% path serves the stylesheet and the fonts alike and nothing has to reason about
% the encoding of a woff2. Failing here fails the build, which is where a missing
% UI file should be noticed.
%
% A string rather than the code list this used to be, and the difference is not
% stylistic. A code list costs about seventy-five times the size of the file it
% came from -- reading the 2.5 MB WebAssembly bundle that way peaked at 194 MB,
% against 19 MB as a string -- and the page cannot be served at all without that
% bundle. SWI stores a string of bytes as a byte array, and format/2's ~s writes
% one back out unchanged; a font round-trips byte for byte, which the suite
% asserts.
%
% Everything under web/ except index.html is generated by `npm run build` and
% committed; see the notes in app.src.css, map.src.js and tools/build_image.mjs.
% Nothing in the image knows about npm.
%
% The page runs the validator itself, compiled to WebAssembly, and does not call
% the API below -- which is why the two largest assets here are a Prolog engine
% and a Prolog image. The endpoints remain for programmatic callers.
:- dynamic asset/3.               % Path, ContentType, Bytes

asset_file('index.html',                        '/',                                 'text/html; charset=UTF-8').
asset_file('app.css',                           '/app.css',                          'text/css; charset=UTF-8').
asset_file('app.js',                            '/app.js',                           'text/javascript; charset=UTF-8').
asset_file('api.js',                            '/api.js',                           'text/javascript; charset=UTF-8').
asset_file('worker.js',                         '/worker.js',                        'text/javascript; charset=UTF-8').
asset_file('map.js',                            '/map.js',                           'text/javascript; charset=UTF-8').
asset_file('rtw.pvm',                           '/rtw.pvm',                          'application/octet-stream').
asset_file('vendor/swipl-bundle-no-data.js',    '/vendor/swipl-bundle-no-data.js',   'text/javascript; charset=UTF-8').
asset_file('fonts/archivo-latin-var.woff2',     '/fonts/archivo-latin-var.woff2',    'font/woff2').
asset_file('fonts/martianmono-latin-var.woff2', '/fonts/martianmono-latin-var.woff2', 'font/woff2').

:- dynamic asset_root/1.          % where they were read from, for dev mode only

:- prolog_load_context(directory, Dir),
   file_directory_name(Dir, Root),
   atomic_list_concat([Root, '/web/'], Web),
   assertz(asset_root(Web)),
   forall(asset_file(File, Path, Type),
          ( atomic_list_concat([Web, File], Abs),
            read_file_to_string(Abs, Bytes, [encoding(octet)]),
            assertz(asset(Path, Type, Bytes)) )).

% Development only. Reading the page into the program is right for a deployment
% and wrong for the twenty minutes you spend changing a stylesheet, because
% every edit needs a restart to appear. With RTW_DEV_ASSETS set, each request
% re-reads the file instead, and replies become uncacheable so the browser does
% not undo the point of it.
%
% It is opt-in, announced at startup, and falls back to the copy in the program
% if the file has gone: the build path it uses is the one baked in at compile
% time, which is correct on the machine that did the compiling and nowhere else.
:- dynamic dev_assets/0.

:- initialization(configure_dev_assets).

configure_dev_assets :-
    (   getenv('RTW_DEV_ASSETS', V),
        V \== '', V \== '0', V \== 'false'
    ->  assertz(dev_assets),
        asset_root(Root),
        print_message(warning, rtw_dev_assets(Root))
    ;   true
    ).

% Access logging is off unless RTW_HTTP_LOG names a file. library(http/http_log)
% otherwise defaults to writing httpd.log into the working directory, which is
% not something merely loading this file should do.
:- initialization(configure_logging).

configure_logging :-
    (   getenv('RTW_HTTP_LOG', File), File \== ''
    ->  set_setting(http:logfile, File)
    ;   set_setting(http:logfile, '')
    ).

% Validation is the only expensive handler: it runs under a time limit and is
% quadratic in the segment count. Sharing the server's default five workers
% with it means five slow requests stop /api/health answering, and a load
% balancer then takes the instance out of service over something that is not an
% outage. Its own bounded pool keeps the cheap endpoints responsive, and a full
% queue is refused rather than accumulated -- SWI maps threads_in_pool/1 to a
% 503, which is the honest answer to "we are at capacity".
:- multifile thread_pool:create_pool/1.

thread_pool:create_pool(rtw_validate) :-
    limit(validate_workers, Workers),
    limit(validate_backlog, Backlog),
    thread_pool_create(rtw_validate, Workers, [backlog(Backlog)]).

:- http_handler(root(.),            home,     [method(get)]).
:- http_handler(root('app.css'),    static,   [method(get)]).
:- http_handler(root('app.js'),     static,   [method(get)]).
:- http_handler(root('api.js'),     static,   [method(get)]).
:- http_handler(root('worker.js'),  static,   [method(get)]).
:- http_handler(root('map.js'),     static,   [method(get)]).
:- http_handler(root('rtw.pvm'),    static,   [method(get)]).
% One prefix handler each for the font and vendor directories. Neither resolves
% anything from the filesystem -- the path is looked up in the table above and
% anything absent is a 404 -- so there is no traversal to defend against.
:- http_handler(root(fonts),        static,   [prefix, method(get)]).
:- http_handler(root(vendor),       static,   [prefix, method(get)]).
:- http_handler(root(api/health),   health,   [method(get)]).
:- http_handler(root(api/ruleset),  ruleset,  [method(get)]).
% The counterpart of /api/ruleset for the earning side: the programmes, their
% currencies and where each table was read. It exists so the page hardcodes no
% programme, for the same reason it hardcodes no rule.
:- http_handler(root(api/programs), programs, [method(get)]).
:- http_handler(root(api/airports), airports, [method(get)]).
:- http_handler(root(api/validate), validate_endpoint,
                [method(post), methods([post, options]), spawn(rtw_validate)]).
% Not on the validate pool: this one runs no rules, only the annotation pass,
% which is linear in a segment count the reader already caps.
:- http_handler(root(api/routing), routing_endpoint,
                [method(post), methods([post, options])]).
% Earning runs no rules either, but it is linear in segments times programmes
% times currencies and reaches a table on every step, so it shares the bounded
% pool rather than the server's default workers.
:- http_handler(root(api/earn), earn_endpoint,
                [method(post), methods([post, options]), spawn(rtw_validate)]).

%! server(+Port) is det.
server(Port) :-
    http_server(http_dispatch, [port(Port)]).

%! stop_server(+Port) is det.
stop_server(Port) :-
    http_stop_server(Port, []).

% --- endpoints -------------------------------------------------------------

% The page talks to the endpoints below and hardcodes no rule data -- limits, the
% carrier list, the city codes and the routing grammar all come from
% /api/ruleset, so the UI cannot drift from the ruleset it is describing.
home(Request) :-
    reply_asset('/', Request).

static(Request) :-
    memberchk(path(Path), Request),
    (   asset(Path, _, _)
    ->  reply_asset(Path, Request)
    ;   http_404([], Request)
    ).

% Headers, then the bytes verbatim. The stream is switched to octet after the
% headers are written: they are ASCII either way, and the body must not be
% re-encoded on its way out or a woff2 arrives corrupt.
%
% Caching splits on whether a file's name identifies its contents. The fonts are
% never edited in place -- a different font means a differently named file -- so
% they are immutable. Everything else is rebuilt under the name it already had,
% so it is revalidated every load. That now includes a 2.5 MB engine and a 400 KB
% image, but revalidating an unchanged file costs a 304 rather than the file, and
% these are served over what is usually loopback.
% Content-Length is left to the HTTP layer, which buffers the reply and counts it
% for us; writing one here as well produced the header twice.
reply_asset(Path, _Request) :-
    asset(Path, Type, Baked),
    (   from_disk(Path, Fresh)
    ->  Bytes = Fresh
    ;   Bytes = Baked
    ),
    cache_control(Type, Cache),
    format('Content-Type: ~w~n', [Type]),
    format('Cache-Control: ~w~n~n', [Cache]),
    set_stream(current_output, encoding(octet)),
    format('~s', [Bytes]).

from_disk(Path, Bytes) :-
    dev_assets,
    asset_file(File, Path, _),
    asset_root(Root),
    atomic_list_concat([Root, File], Abs),
    catch(read_file_to_string(Abs, Bytes, [encoding(octet)]), _, fail).

% A dev reply must not be cached at all, or the next edit is invisible for
% reasons that take an hour to find.
cache_control(_, 'no-store') :- dev_assets, !.
cache_control('font/woff2', 'public, max-age=31536000, immutable') :- !.
cache_control(_,            'no-cache').

health(_Request) :-
    cors_enable,
    ruleset_version(V),
    reply_json_dict(_{ status: ok, rulesetVersion: V }).

ruleset(_Request) :-
    cors_enable,
    ruleset_json(Dict),
    reply_json_dict(Dict).

programs(_Request) :-
    cors_enable,
    programs_json(Dict),
    reply_json_dict(Dict).

airports(Request) :-
    cors_enable,
    http_parameters(Request,
                    [ q(Q, [default('')]),
                      limit(Limit, [integer, default(20)])
                    ]),
    Capped is max(1, min(Limit, 100)),
    (   Q == ''
    ->  Results = []
    ;   airport_search(Q, Capped, Codes),
        maplist(airport_json, Codes, Results)
    ),
    reply_json_dict(_{ query: Q, results: Results }).

validate_endpoint(Request) :-
    cors_enable,
    (   memberchk(method(options), Request)
    ->  reply_json_dict(_{}, [status(200)])
    ;   catch_with_backtrace(validate_request(Request), Error,
                             reply_error(Error, Request))
    ).

% The same itinerary written as a routing. It exists so that the browser does
% not have to compose one: that would be a second definition of the grammar,
% and the only one with no test behind it. Every report already carries the
% routing in its annotations; this is for the case where you want it without
% asking for a verdict.
routing_endpoint(Request) :-
    cors_enable,
    (   memberchk(method(options), Request)
    ->  reply_json_dict(_{}, [status(200)])
    ;   catch_with_backtrace(routing_request(Request), Error,
                             reply_error(Error, Request))
    ).

% What the journey earns, which runs no fare rules at all: a journey that cannot
% be sold can still be priced for its earn, and one that is perfectly valid can
% be unpriceable. That is why it is its own endpoint rather than a field on the
% report -- see PLANS/05-loyalty-earning.md.
earn_endpoint(Request) :-
    cors_enable,
    (   memberchk(method(options), Request)
    ->  reply_json_dict(_{}, [status(200)])
    ;   catch_with_backtrace(earn_request(Request), Error,
                             reply_error(Error, Request))
    ).

earn_request(Request) :-
    check_body_size(Request),
    http_read_json_dict(Request, Dict, [value_string_as(string)]),
    limit(request_time_limit_seconds, Seconds),
    call_with_time_limit(Seconds, build_earn(Dict, Json)),
    reply_json_dict(Json).

build_earn(Dict, Json) :-
    asked_programs(Dict, Asked),
    resolve_programs(Asked, Programs),
    itinerary_from_json(Dict, Itin),
    annotate(Itin, A),
    earn(A, Programs, Report),
    earn_json(Report, Json).

% Absent or empty means every registered programme, which is the useful default:
% "where should I credit this ticket?" is the question having more than one is
% for, and it cannot be asked one programme at a time.
asked_programs(Dict, Asked) :-
    (   get_dict(programs, Dict, List), is_list(List)
    ->  maplist([V, A]>>( atom_string(A, V) ), List, Asked)
    ;   get_dict(programs, Dict, V), V \== null
    ->  throw(input_error('"programs" must be a list of programme ids.'))
    ;   Asked = []
    ).

routing_request(Request) :-
    check_body_size(Request),
    http_read_json_dict(Request, Dict, [value_string_as(string)]),
    itinerary_from_json(Dict, Itin),
    annotate(Itin, A),
    (   annotated_route(A, Route)
    ->  reply_json_dict(_{ route: Route })
    ;   no_routing_message(A, Message),
        throw(input_error(Message))
    ).

validate_request(Request) :-
    check_body_size(Request),
    http_read_json_dict(Request, Dict, [value_string_as(string)]),
    % The report is built under a time limit and replied outside it, so a
    % timeout can never leave a half-written response on the wire.
    limit(request_time_limit_seconds, Seconds),
    call_with_time_limit(Seconds, build_report(Dict, Json)),
    reply_json_dict(Json).

build_report(Dict, Json) :-
    itinerary_from_json(Dict, Itin),
    validate_annotated(Itin, Report, A),
    annotations_json(A, Annotations),
    report_json(Report, _{ annotations: Annotations }, Json).

% Refuse an oversized body before reading it rather than after. The declared
% length is what SWI will read, so checking it here is the cheap guard; the
% segment cap in io/json_in.pl is the one that bounds the actual work.
check_body_size(Request) :-
    limit(max_request_bytes, Max),
    (   memberchk(content_length(Length), Request),
        Length > Max
    ->  throw(request_too_large(Length, Max))
    ;   true
    ).

% Malformed input is a 400 with a structured body; anything else is a bug in a
% rule and is reported as a 500 rather than being swallowed into a verdict.
%
% The four cases below describe the caller's own request back to them, which is
% information they already have. The fallback deliberately does not: see
% log_internal_error/2.
%
% The mapping is kept separate from the writing so that what the client is
% told can be tested without an HTTP context; test_json.pl asserts that the
% fallback body carries nothing from the exception term.
% The status is decided once and then asked about. Calling error_reply/3 a
% second time with 500 bound would match the catch-all clause for *every*
% exception, and log each malformed request as an internal failure.
reply_error(Error, Request) :-
    error_reply(Error, Status, Dict),
    (   Status == 500
    ->  log_internal_error(Error, Request)
    ;   true
    ),
    reply_json_dict(Dict, [status(Status)]).

%! error_reply(+Error, -Status, -Dict) is det.
error_reply(input_error(Message), 400,
            _{ error: 'invalid_request', message: Message }) :- !.
error_reply(request_too_large(Length, Max), 413,
            _{ error: 'request_too_large', message: M }) :- !,
    format(atom(M), 'Request body is ~d bytes; the maximum is ~d.', [Length, Max]).
error_reply(time_limit_exceeded, 503,
            _{ error: 'timeout',
               message: 'Validation exceeded its time limit.' }) :- !.
error_reply(http_reply(_), 400,
            _{ error: 'invalid_request',
               message: 'Request body must be JSON.' }) :- !.
error_reply(_, 500,
            _{ error: 'internal_error',
               message: 'The validator failed on this request. The failure has been logged.' }).

% Logged in full server-side, opaque to the client. This path only fires on a
% bug, and the raw term plus its backtrace is exactly what a developer needs --
% but it is also a description of the validator's internals, and handing that
% to an unauthenticated caller is the hazard library(http/http_error) exists to
% warn about. stderr is the right destination: systemd and Docker both collect
% it, and neither needs a log file managed inside the container.
% The term is printed by us rather than left to print_message/2, which renders
% anything without a message clause as "Unknown message". Standard errors are
% then printed a second time so their backtrace -- collected by
% catch_with_backtrace/3 -- is rendered too.
log_internal_error(Error, Request) :-
    (   memberchk(path(Path), Request) -> true ; Path = unknown ),
    print_message(error, rtw_request_failed(Path, Error)),
    (   Error = error(_, _)
    ->  print_message(error, Error)
    ;   true
    ).

:- multifile prolog:message//1.

prolog:message(rtw_request_failed(Path, Error)) -->
    [ 'Unhandled error while serving ~w; replying 500: ~p'-[Path, Error] ].

prolog:message(rtw_dev_assets(Root)) -->
    [ 'RTW_DEV_ASSETS is set: the page, stylesheet, script and fonts are being'-[], nl,
      're-read from ~w on every request and served uncacheable.'-[Root], nl,
      'This is for development. Unset it in production.'-[] ].
