#!/usr/bin/env swipl
% build_airports.pl -- OurAirports CSV -> data/generated/airports.pl
%
%   swipl prolog/tools/build_airports.pl -- <airports.csv> [out.pl]
%
% Source: https://davidmegginson.github.io/ourairports-data/airports.csv
%
% The output is committed to git. Regenerating is a manual step so that a
% change in upstream geography arrives as a reviewable diff rather than as a
% silent behaviour change, and so a fresh clone runs offline.

:- module(build_airports, [main/0, build/2]).

:- use_module(library(csv)).
:- use_module(library(apply)).
:- use_module(library(lists)).

main :-
    current_prolog_flag(argv, Argv),
    (   Argv = [In|Rest]
    ->  (   Rest = [Out|_] -> true ; default_out(Out) ),
        build(In, Out)
    ;   format(user_error,
               "usage: swipl prolog/tools/build_airports.pl -- <airports.csv> [out.pl]~n", []),
        halt(2)
    ).

default_out(Out) :-
    source_file(main, Here),
    file_directory_name(Here, ToolsDir),
    file_directory_name(ToolsDir, PrologDir),
    atomic_list_concat([PrologDir, '/data/generated/airports.pl'], Out).

%! build(+CsvFile, +OutFile) is det.
build(In, Out) :-
    findall(K, airport_key(In, K), Keys0),
    sort(Keys0, Keys),                 % by IATA, then by type rank
    dedupe_by_iata(Keys, Kept),
    length(Kept, N),
    setup_call_cleanup(
        open(Out, write, S, [encoding(utf8)]),
        write_file(S, Kept, N),
        close(S)),
    format(user_error, "wrote ~d airports to ~w~n", [N, Out]).

% Row layout confirmed against the file header:
%   1 id  2 ident  3 type  4 name  5 latitude_deg  6 longitude_deg
%   7 elevation_ft  8 continent  9 iso_country  10 iso_region
%   11 municipality  12 scheduled_service  13 icao_code  14 iata_code ...
%
% Column 8 (`continent`) is deliberately NOT read: it is physical geography and
% disagrees with the fare rule's continents. See data/countries.pl.
airport_key(In, k(Iata, Rank, Country, Region, City, Lat, Lon)) :-
    csv_read_file_row(In, Row, [functor(row), arity(19), convert(false), line(Line)]),
    Line > 1,
    Row = row(_, _, Type0, Name0, Lat0, Lon0, _, _, Country0, Region0,
              City0, Sched0, _, Iata0, _, _, _, _, _),
    text_atom(Sched0, yes),
    text_atom(Iata0, Iata1), Iata1 \== '',
    type_rank(Type0, Rank),
    downcase_atom(Iata1, Iata),
    text_atom(Country0, Country),
    text_atom(Region0, Region),
    text_atom(Name0, Name),
    text_atom(City0, City0a),
    ( City0a == '' -> City = Name ; City = City0a ),
    number_or(Lat0, 0.0, Lat),
    number_or(Lon0, 0.0, Lon).

% Everything with scheduled service and an IATA code is kept, including
% small_airport: filtering by size drops real scheduled points (Broome and
% Karratha are in the 4(l) city-pair table, and Karratha is only "medium").
% Rank exists solely to pick a winner when two rows share an IATA code.
type_rank(T0, Rank) :-
    text_atom(T0, T),
    (   T == large_airport  -> Rank = 1
    ;   T == medium_airport -> Rank = 2
    ;   T == small_airport  -> Rank = 3
    ;   Rank = 4
    ).

text_atom(X, A) :- atom(X), !, A = X.
text_atom(X, A) :- string(X), !, atom_string(A, X).
text_atom(X, A) :- atom_number(A, X).

number_or(X, _, N) :- number(X), !, N = X.
number_or(X, Default, N) :-
    text_atom(X, A),
    (   atom_number(A, N0) -> N = N0 ; N = Default ).

% The keys arrive from sort/2 ordered by IATA and then by type rank, so every
% row sharing a code is already adjacent and the first of the run is the winner.
% Dropping the rest of the run is therefore one pass over the list.
%
% This used to be an exclude/3 over the whole tail with the lambda
% [k(I,...)]>>(I == Iata), which quietly excluded nothing: >>/2 copies its lambda
% before each call, and Iata -- a free variable of the body rather than a
% parameter -- was renamed with it, so the comparison was always against a fresh
% unbound variable. Declaring it as {Iata}/[k(I,...)]>>(I == Iata) would have
% fixed the copy, but the run is adjacent and the scan is not needed at all.
%
% Nothing downstream noticed because the current CSV happens to give each IATA
% code one scheduled-service row. Had it not, the generated file would have
% carried two airport/6 facts for one code, and every geo lookup built on
% first-argument indexing -- airport_country/2 and the rest -- would have become
% nondeterministic and answered with whichever row came first.
dedupe_by_iata([], []).
dedupe_by_iata([K|Ks], [K|Rest]) :-
    K = k(Iata, _, _, _, _, _, _),
    drop_run(Iata, Ks, Ks1),
    dedupe_by_iata(Ks1, Rest).

drop_run(Iata, [k(Iata, _, _, _, _, _, _)|Ks], Rest) :- !, drop_run(Iata, Ks, Rest).
drop_run(_, Ks, Ks).

write_file(S, Keys, N) :-
    format(S, "% Generated by prolog/tools/build_airports.pl -- do not edit by hand.~n", []),
    format(S, "%~n", []),
    format(S, "% Source: https://davidmegginson.github.io/ourairports-data/airports.csv~n", []),
    format(S, "% Filter: scheduled_service = yes, non-empty iata_code.~n", []),
    format(S, "% ~d airports.~n", [N]),
    format(S, "%~n", []),
    format(S, "%   airport(IataCode, IsoCountry, IsoRegion, City, Lat, Lon)~n", []),
    format(S, "%~n", []),
    format(S, "% IsoRegion is what makes the sub-country splits possible (Russia at the~n", []),
    format(S, "% Urals, Hawaii and Alaska, the 4(k) transcontinental columns). Coordinates~n", []),
    format(S, "% are carried for the Urals split and for route drawing in the web UI.~n~n", []),
    % Several hundred city names are non-ASCII, and SWI reads source files in
    % the locale encoding unless told otherwise. Without this a container or a
    % cron job running under LC_ALL=C loads the table mojibaked and serves it
    % that way, which is worse than failing.
    format(S, "% Several hundred city names below are non-ASCII, so the encoding is~n", []),
    format(S, "% declared rather than left to the locale of whoever loads the file.~n", []),
    format(S, ":- encoding(utf8).~n~n", []),
    forall(member(k(Iata, _, Country, Region, City, Lat, Lon), Keys),
           format(S, "airport(~q, ~q, ~q, ~q, ~w, ~w).~n",
                  [Iata, Country, Region, City, Lat, Lon])).
